[project]
name = "5-tomar-notas-en-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiomysql>=0.3.2",
    "asyncio>=4.0.0",
    "fastapi[standard]>=0.141.1",
    "language-tool-python>=3.4.0",
    "markdown>=3.10.2",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.51",
]

[tool.fastapi]
entrypoint = "src.main:app"
