[project]
name = "5-tomar-notas-en-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "boto3>=1.43.67",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.9.1",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "resend>=2.35.0",
    "sqladmin>=0.30.0",
    "sqlalchemy>=2.0.51",
    "wtform>=1.0",
    "wtforms>=3.2.2",
]

[tool.fastapi]
entrypoint = "src.main:app"

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
