"""se añadio la regla para eliminar en cascada la relacion padre e hija con reservation y notification

Revision ID: 6ffa1c400ff4
Revises: af2d76c03f56
Create Date: 2026-08-12 14:28:57.027845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffa1c400ff4'
down_revision: Union[str, Sequence[str], None] = 'af2d76c03f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notifications_reservation_id_reservations'), 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notifications_reservation_id_reservations'), 'notifications', 'reservations', ['reservation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notifications_reservation_id_reservations'), 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notifications_reservation_id_reservations'), 'notifications', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###
