"""se añadio la columna de codigo para referenciarciar las reservas para una busqueda mas rapida

Revision ID: 8f78f4fcd892
Revises: 6ffa1c400ff4
Create Date: 2026-08-12 14:31:10.355095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f78f4fcd892'
down_revision: Union[str, Sequence[str], None] = '6ffa1c400ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('code_reservation', sa.CHAR(length=10), nullable=False))
    op.create_unique_constraint(op.f('uq_reservations_code_reservation'), 'reservations', ['code_reservation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_reservations_code_reservation'), 'reservations', type_='unique')
    op.drop_column('reservations', 'code_reservation')
    # ### end Alembic commands ###
