"""se agrego la conexion entre notificaciones y las reservas

Revision ID: af2d76c03f56
Revises: c75def7fdef6
Create Date: 2026-08-11 13:19:58.546022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2d76c03f56'
down_revision: Union[str, Sequence[str], None] = 'c75def7fdef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_reservation_id'), 'notifications', ['reservation_id'], unique=False)
    op.create_foreign_key(op.f('fk_notifications_reservation_id_reservations'), 'notifications', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notifications_reservation_id_reservations'), 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_reservation_id'), table_name='notifications')
    op.drop_column('notifications', 'reservation_id')
    # ### end Alembic commands ###
