"""se incluyo la columna en User para aceptar una URL publico a un BUCKET para almacenar imagenes para avatars de los usuarios

Revision ID: c75def7fdef6
Revises: b1e149cfa0b0
Create Date: 2026-08-08 19:00:30.145331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75def7fdef6'
down_revision: Union[str, Sequence[str], None] = 'b1e149cfa0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
