"""quitar la columna code_reservation como no obligatoria para que los test ya escritos puedan pasar

Revision ID: eefd48919ebb
Revises: 8f78f4fcd892
Create Date: 2026-08-12 18:23:59.702354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefd48919ebb'
down_revision: Union[str, Sequence[str], None] = '8f78f4fcd892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'code_reservation',
               existing_type=sa.CHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'code_reservation',
               existing_type=sa.CHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
